CarnesDonFernando/FronEnd-Admin/Models/RestauranteViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FrontEnd.Models
{
    public class RestauranteViewModel
    {
        [Required]
        public int IdRestaurante { get; set; }



        [Required(ErrorMessage = "El campo es obligatorio.")]
        [Display(Name = "Nombre del restaurante")]
        [StringLength(30, ErrorMessage = "El campo no debe tener más de 30 caracteres.")]
        public string NombreRestaurante { get; set; } = null!;

        [Required(ErrorMessage = "El campo es obligatorio.")]
        [Display(Name = "Ubicacion del restaurante")]
        [StringLength(50, ErrorMessage = "El campo no debe tener más de 50 caracteres.")]
        public string Ubicacion { get; set; } = null!;

        [Required(ErrorMessage = "El campo es obligatorio.")]
        [Display(Name = "Horario del restaurante")]
        [StringLength(50, ErrorMessage = "El campo no debe tener más de 50 caracteres.")]
        public string Horario { get; set; } = null!;

        [Required(ErrorMessage = "El campo es obligatorio.")]
        [Display(Name = "Url del restaurante")]
        public string UrlImg { get; set; } = null!;

        [MinLength(8, ErrorMessage = "Debe especificar un telefono valido")]
        [Required(ErrorMessage = "El campo es obligatorio.")]
        public string Telefono { get; set; } = null!;

    }
}

CarnesDonFernando/FronEnd-Admin/Controllers/RestauranteController.cs
using FrontEnd.Helpers;
using FrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class RestauranteController : Controller
    {
        RestauranteHelper restauranteHelper;

        // GET: RestauranteController
        public ActionResult Index()
        {
            restauranteHelper = new RestauranteHelper();
            List<RestauranteViewModel> lista = restauranteHelper.GetAll();

            return View(lista);
        }

        // GET: RestauranteController/Details/5
        public ActionResult Details(int id)
        {
            RestauranteViewModel restaurante = restauranteHelper.Get(id);

            return View(restaurante);
        }

        // GET: RestauranteController/Create
        public ActionResult Create()
        {
            if (HttpContext.Session.GetString("role") is not null)
            {
                if (HttpContext.Session.GetString("role").Equals("Admin"))
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Error", "Home");
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }

        // POST: RestauranteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RestauranteViewModel restaurante)
        {
            try
            {
                if (HttpContext.Session.GetString("role") is not null)
                {
                    if (HttpContext.Session.GetString("role").Equals("Admin"))
                    {
                        restauranteHelper = new RestauranteHelper(HttpContext.Session.GetString("token"));
                        restaurante = restauranteHelper.Create(restaurante);
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }
                else
                {
                    return RedirectToAction("Login", "Usuario");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: RestauranteController/Edit/5
        public ActionResult Edit(int id)
        {
            if (HttpContext.Session.GetString("role") is not null)
            {
                if (HttpContext.Session.GetString("role").Equals("Admin"))
                {
                    restauranteHelper = new RestauranteHelper(HttpContext.Session.GetString("token"));
                    RestauranteViewModel local = restauranteHelper.Get(id);
                    return View(local);
                }
                else
                {
                    return RedirectToAction("Error", "Home");
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }

        // POST: RestauranteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RestauranteViewModel restaurante)
        {
            try
            {
                if (HttpContext.Session.GetString("role") is not null)
                {
                    if (HttpContext.Session.GetString("role").Equals("Admin"))
                    {
                        restauranteHelper = new RestauranteHelper(HttpContext.Session.GetString("token"));
                        restaurante = restauranteHelper.Edit(restaurante);
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }
                else
                {
                    return RedirectToAction("Login", "Usuario");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: RestauranteController/Delete/5
       /* public ActionResult Delete(int id)
        {
            RestauranteViewModel restaurante = restauranteHelper.Get(id);

            return View(restaurante);
        }*/

        // POST: RestauranteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int idRestaurante)
        {
            try
            {
                if (HttpContext.Session.GetString("role") is not null)
                {
                    if (HttpContext.Session.GetString("role").Equals("Admin"))
                    {
                        restauranteHelper = new RestauranteHelper(HttpContext.Session.GetString("token"));
                        restauranteHelper.Delete(idRestaurante);
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }
                else
                {
                    return RedirectToAction("Login", "Usuario");
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

CarnesDonFernando/FronEnd-Admin/Views/Restaurante/Create.cshtml
@model FrontEnd.Models.RestauranteViewModel

@{
    ViewData["Title"] = "Create";
}

<br />
<br />
<br />
<br />
<div class="container-fluid">
    <div class="row abs-center form-factura">
        <form asp-action="Create" id="formularioMio" method="post">
            <div class="col-md">

                <form asp-action="Create" id="formularioMio" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="NombreRestaurante" class="control-label"></label>
                                <input required asp-for="NombreRestaurante" class="form-control" />
                                <span asp-validation-for="NombreRestaurante" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="Ubicacion" class="control-label"></label>
                                <input required asp-for="Ubicacion" class="form-control" />
                                <span asp-validation-for="Ubicacion" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="Horario" class="control-label"></label>
                                <input required asp-for="Horario" class="form-control" />
                                <span asp-validation-for="Horario" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="Telefono" class="control-label"></label>
                                <input required maxlength="9" asp-for="Telefono" class="form-control" />
                                <span asp-validation-for="Telefono" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="UrlImg" class="control-label"></label>
                            <input required asp-for="UrlImg" class="form-control" />
                            <span asp-validation-for="UrlImg" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="shopping-cart-footer" style="margin-top: 50px; border-color: white">
                        <div class="column">
                            <script>
                                var formularioMio = document.getElementById('formularioMio');
                                formularioMio.addEventListener('submit', function (event) {
                                    event.preventDefault();
                                    mostrarMensaje();
                                });
                                function mostrarMensaje() {
                                    //event.preventDefault();
                                    if (formularioMio.checkValidity()) {
                                        Swal.fire({
                                            title: '¡Restaurante creado!',
                                            text: 'El restaurante se creó con exito',
                                            icon: 'success',
                                            confirmButtonColor: '#AD2022',
                                            confirmButtonText: 'Entendido'
                                        }).then(function () {
                                            // document.forms[0].submit();
                                            formularioMio.submit();
                                        });
                                    }
                                }
                            </script>

                            <a href="http://localhost:8000/Restaurante" class="btnCatalogo btn">Regresar</a>
                            <input type="submit" onclick="mostrarMensaje()" value="Crear restaurante" class="btn btnCatalogo" />
                        </div>
                    </div>

                </form>

            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarnesDonFernando/FronEnd-Admin/Views/Restaurante/Delete.cshtml
@model FrontEnd.Models.RestauranteViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RestauranteViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdRestaurante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdRestaurante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreRestaurante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreRestaurante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Horario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Horario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UrlImg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UrlImg)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        @Html.HiddenFor(Model=>Model.IdRestaurante)
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CarnesDonFernando/FronEnd-Admin/Views/Restaurante/Details.cshtml
@model FrontEnd.Models.RestauranteViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>RestauranteViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdRestaurante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdRestaurante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreRestaurante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreRestaurante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Horario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Horario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UrlImg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UrlImg)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id=Model.IdRestaurante }) |
    <a asp-action="Index">Back to List</a>
</div>

CarnesDonFernando/FronEnd-Admin/Views/Restaurante/Edit.cshtml
@model FrontEnd.Models.RestauranteViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="container-fluid" style="margin-top:100px">
    <div class="row abs-center form-factura">
        <form asp-action="Edit" id="formularioMio" method="post">
            <div class="col-md">

                <form asp-action="Edit" id="formularioMio" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="NombreRestaurante" class="control-label"></label>
                                <input required asp-for="NombreRestaurante" value="@Model.NombreRestaurante" class="form-control" />
                                <span asp-validation-for="NombreRestaurante" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="Ubicacion" class="control-label"></label>
                                <input required asp-for="Ubicacion" value="@Model.Ubicacion" class="form-control" />
                                <span asp-validation-for="Ubicacion" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="Horario" class="control-label"></label>
                                <input required asp-for="Horario" value="@Model.Horario" class="form-control" />
                                <span asp-validation-for="Horario" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="Telefono" class="control-label"></label>
                                <input required maxlength="9" asp-for="Telefono" value="@Model.Telefono" class="form-control" />
                                <span asp-validation-for="Telefono" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="UrlImg" class="control-label"></label>
                            <input required asp-for="UrlImg" class="form-control" value="@Model.UrlImg" />
                            <span asp-validation-for="UrlImg" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="shopping-cart-footer" style="margin-top: 50px; border-color: white">
                        <div class="column">
                            <input asp-for="IdRestaurante" value="@Model.IdRestaurante" hidden class="form-control" />
                            <script>
                                var formularioMio = document.getElementById('formularioMio');
                                formularioMio.addEventListener('submit', function (event) {
                                    event.preventDefault();
                                    mostrarMensaje();
                                });
                                function mostrarMensaje() {
                                    //event.preventDefault();
                                    if (formularioMio.checkValidity()) {
                                        Swal.fire({
                                            title: '¡Restaurante actualizado!',
                                            text: 'El restaurante se actualizó con exito',
                                            icon: 'success',
                                            confirmButtonColor: '#AD2022',
                                            confirmButtonText: 'Entendido'
                                        }).then(function () {
                                            // document.forms[0].submit();
                                            formularioMio.submit();
                                        });
                                    }
                                }
                            </script>

                            <a href="http://localhost:8000/Restaurante" class="btnCatalogo btn">Regresar</a>
                            <input type="submit" onclick="mostrarMensaje()" value="Actualizar restaurante" class="btn btnCatalogo" />
                        </div>
                    </div>
                </form>

            </div>
        </form>

    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarnesDonFernando/FronEnd-Admin/Views/Restaurante/Index.cshtml
@model IEnumerable<FrontEnd.Models.RestauranteViewModel>

@{
    ViewData["Title"] = "Index";
}


<h1 class="display-4 text-center tituloPaginaIndex" style="margin-top: 200px;">Restaurante</h1>


<div class="container-fluid">
    <div class="row g-0 bg-light position-relative vinculoDonFer">

        <div class="col-md-6 p-4 ps-md-0">
            <h5 class="card-title subTituloResta subtituloPaginaIndex subTituloNosotros">Disfrute de exquisitos platillos</h5>
            <p>
                En el restaurante Don Fernando disfrutará de una experiencia gastronómica para todos los gustos, gracias a la variedad de platillos
                y cortes de carne que son preparados cuidadosamente por expertos parrilleros. Además, encontrará el ambiente ideal para compartir
                un rato agradable y saborear carne 100% costarricense, libre de hormonas, antibióticos y aditivos.
            </p>
        </div>
        <div class="col-md-6 mb-md-0 p-md-4">
            <img src="~/Imagenes/imgNosotros/finca-carbono-neutro.jpg" class="w-100" style="max-width: 600px" />
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row-5 justify-content-center">
        @Html.ActionLink("Agregar restaurante", "Create", "Restaurante")
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var item in Model)
        {
            <div class="col">

                <div class="card  tarjetasCatalogoInfo" style="max-width: 350px">

                    <div class="card-body" style="background-color: #D20005">
                        <h5 class="card-title tituloTienda"> @Html.DisplayFor(modelItem => item.NombreRestaurante)</h5>
                        <p class="card-text textoTienda"> @Html.DisplayFor(modelItem => item.Ubicacion)</p>
                        <p class="card-text textoTienda"> @Html.DisplayFor(modelItem => item.Telefono)</p>
                        <p class="card-text textoTienda"> @Html.DisplayFor(modelItem => item.Horario)</p>
                    </div>
                    <img src="@Url.Content(@item.UrlImg)" class="card-img-top" />
                    <div class="d-flex justify-content-around" style="margin-top: 12px;">

                        <form asp-action="Delete" id="formularioMio-@item.IdRestaurante" method="post">
                            <script>
                                var formularioMio = document.getElementById('formularioMio-@item.IdRestaurante');
                                formularioMio.addEventListener('submit', function (event) {
                                    event.preventDefault();
                                    mostrarMensaje();
                                });
                                function mostrarMensaje(idLocal) {
                                    Swal.fire({
                                        title: '¿Esta seguro?',
                                        text: "Se eliminara el restaurante",
                                        icon: 'warning',
                                        showCancelButton: true,
                                        confirmButtonColor: '#d33',
                                        cancelButtonColor: '#3085d6',
                                        confirmButtonText: 'Eliminar',
                                        cancelButtonText: 'Cancelar'
                                    }).then((result) => {
                                        if (result.isConfirmed) {
                                            Swal.fire(
                                                'Eliminado!',
                                                'El restaurante se ha eliminado con exito',
                                                'success'
                                            ).then(function () {
                                                //document.forms[7].submit();
                                                var formularioMio = document.getElementById('formularioMio-' + idLocal);
                                                formularioMio.submit();
                                            });

                                        }
                                    })
                                }
                            </script>
                            <input value="@item.IdRestaurante" name="idRestaurante" hidden />
                            <input onclick="mostrarMensaje(@item.IdRestaurante)" type="button" value="Eliminar restaurante" class="btn btnCatalogo" />
                            @Html.ActionLink("Editar restaurante", "Edit", "Restaurante", new {id = item.IdRestaurante}, new { @class = "btnCatalogo btn " })
                        </form>
                    </div>
                </div>

            </div>
        }
    </div>
</div>
<br />
<br />
<br />
<br />
<br />
<br />